# Generated by Django 5.0.2 on 2024-02-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='number',
            new_name='phone',
        ),
    ]
